# Configuration file for meta-heuristic topology optimization framework

suppress_grid_image_plot: False
suppress_grid_image_save: False
save_as_pdf: False

buildings_map:
  dimension: 2

semantic_map:
  dimension: 2

streets_map:
  dimension: 2

risk_map:
  dimension: 3

noise_map:
  dimension: 3

obstacle_map:
  dimension: 3

radio_disturbance_map:
  dimension: 3

nfa_map:
  dimension: 3

clearance_height_map:
  dimension: 2

radio_signal_towers_map:
  dimension: 2

minimum_flight_height_map:
  dimension: 3

legality_map:
  dimension: 3





