name: CI/CD Pipeline

on:
  push:         # Run pipeline on push to any branch
    branches:
      - main
  pull_request: # Run pipeline on PRs to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Fetch repository code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.9"  # Specify Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_ci_cd.txt

      - name: Run Ruff Formatting
        run: ruff format

      - name: Run Ruff Linting
        run: ruff check

      - name: Run mypy Type Checking
        run: |
          mypy --install-types
          mypy --ignore-missing-imports .

      - name: Run Tests
        run: |
          pytest

  deploy:
    needs: build-and-test  # Run deploy only if build-and-test succeeds
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Placeholder
        run: |
          echo "Deployment step goes here."
